### ISSUE TITLE
Testing a Pojo with enum fields results in a ClassNotFoundException

### ISSUE THREAD

**Issue by toaster91** [danhagberg/pojot#12]
I have a simple Pojo that includes a field that is an enumeration.  Running TestAid with this class results in a NoSuchMethodException.

Here is the sample class and a TestNG driver
```java
import static org.testng.Assert.assertTrue;

import java.util.List;
import java.util.Objects;

import org.testng.annotations.Test;

import net.digitaltsunami.pojot.TestAid;

public class PojotTest {

	public enum TestEnum {
		ENUM1(), ENUM2()
	}

	public class TestEnumConsumer {

		private String name = null;
		private TestEnum enumField = null;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public TestEnum getEnumField() {
			return enumField;
		}

		public void setEnumField(TestEnum enumField) {
			this.enumField = enumField;
		}

		@Override
		public int hashCode() {
			return Objects.hash(name, enumField);
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) {
				return true;
			}
			if (o == null || getClass() != o.getClass()) {
				return false;
			}
			TestEnumConsumer testEnumConsumer = (TestEnumConsumer) o;
			return Objects.equals(name, testEnumConsumer.name) && Objects.equals(enumField, testEnumConsumer.enumField);
		}

	}

	@Test
	public void testEnum() throws Exception {
		List<String> errors = new TestAid<TestEnumConsumer>(TestEnumConsumer.class)
				.includeInEquals( "name", "enumField")
				.validate();
		assertTrue(errors.isEmpty(), errors.toString());

	}

}
```

The full stack of the test failure is:
```
net.digitaltsunami.pojot.TestAidException: Error during Getter testing
	at net.digitaltsunami.pojot.GetterTestRunner.runTests(GetterTestRunner.java:48)
	at net.digitaltsunami.pojot.TestAid.runGetterTests(TestAid.java:241)
	at net.digitaltsunami.pojot.TestAid.validate(TestAid.java:223)
	at com.concur.imaging.shared.beans.domain.PojotTest.testEnum(PojotTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
Caused by: java.lang.InstantiationException: com.concur.imaging.shared.beans.domain.PojotTest$TestEnumConsumer
	at java.lang.Class.newInstance(Class.java:427)
	at net.digitaltsunami.pojot.GetterTestRunner.runTests(GetterTestRunner.java:44)
	... 27 more
Caused by: java.lang.NoSuchMethodException: com.concur.imaging.shared.beans.domain.PojotTest$TestEnumConsumer.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 28 more
```

**Comment by danhagberg** [comment]
Added ability to test a class with enum properties.  Code released with version 1.2.2
Note that the example code above will still not work as the error is on the constructor for the inner class of TestEnumConsumer.
